### ISSUE TITLE
Suspicious flownet warmup logs

### ISSUE THREAD

**Issue by LeftAttention** [cuiaiyu/dressing-in-order#8]
During the flow net warm up. I am getting the following logs. I am not understanding why all the values are zero.

```
[flownet_warmup][iter-50]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-100]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-150]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-200]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-250]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-300]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-350]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-400]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-450]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-500]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-550]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-600]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-650]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-700]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-750]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-800]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-850]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-900]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-950]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1000]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1050]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1100]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1150]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1200]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1250]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1300]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1350]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1400]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1450]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1500]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1550]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1600]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1650]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1700]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1750]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1800]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1850]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1900]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-1950]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
[flownet_warmup][iter-2000]G_GAN_pose: 0.0000, G_GAN_content: 0.0000, D_real_pose: 0.0000, D_fake_pose: 0.0000, D_real_content: 0.0000, D_fake_content: 0.0000, rec: 0.0000, per: 0.0000, sty: 0.0000, seg: 0.0000, flow_reg: 0.0000, flow_cor: 2.5285, 
saving the latest model (total_iters 2000)
End of iter 2000 / 120000        Time Taken: 1220 sec
at 2000, compute visuals
```

These are my training parameters. 

```
----------------- Options ---------------
               batch_size: 32                             
                    beta1: 0.5                           
                    beta2: 0.999                         
          checkpoints_dir: checkpoints                   
           continue_train: True                          	[default: False]
                crop_size: 256                           
                 dataroot: data/fashion/                 	[default: data]
             display_freq: 2000                          
                    epoch: latest                        
              epoch_count: 1                             
             flownet_path:                               
               frozen_enc: False                         
           frozen_flownet: False                         
            frozen_models:                               
                g2d_ratio: 0.1                           
                 gan_mode: lsgan                         
                  gpu_ids: 0,1,2,3                         	[default: 0]
                  img_dir: img_highres                   
                init_gain: 0.02                          
                init_type: orthogonal                    	[default: kaiming]
                  isTrain: True                          	[default: None]
                load_iter: 0                             	[default: 0]
             loss_coe_GAN: 1                             
        loss_coe_flow_cor: 2.0                           
        loss_coe_flow_reg: 0.001                         
             loss_coe_per: 0.0                           	[default: 0.2]
             loss_coe_rec: 0.0                           	[default: 2]
             loss_coe_seg: 0.1                           
             loss_coe_sty: 0.0                           	[default: 200]
                       lr: 0.0001                        	[default: 0.001]
           lr_decay_iters: 50                            
                lr_policy: linear                        
           lr_update_unit: 10000                         
           max_batch_size: 16                            
                    model: flow                          	[default: adgan]
                   n_cpus: 8                             	[default: 4]
             n_downsample: 2                             
                 n_epochs: 60000                         
           n_epochs_decay: 60000                         
            n_human_parts: 8                             
                   n_kpts: 18                            
               n_layers_D: 3                             
           n_style_blocks: 4                             
                     name: flownet_warmup                	[default: experiment_name]
                      ndf: 64                            
                     netD: resnet                        
                     netE: adgan                         
                     netG: adgan                         
                      ngf: 64                            
               no_dropout: False                         
            no_trial_test: True                          	[default: False]
                norm_type: instance                      
                  perturb: False                         
                    phase: train                         
                pool_size: 50                            
               print_freq: 50                            	[default: 100]
              progressive: False                         
              random_rate: 1                             
                relu_type: leakyrelu                     
             save_by_iter: False                         
          save_epoch_freq: 20000                         
         save_latest_freq: 2000                          
             segm_dataset:                               
                   square: False                         
                 style_nc: 64                            
                   suffix:                               
                  tex_dir: dtd/images                    
                  verbose: False                         
                   warmup: False                         
----------------- End -------------------
```
